
import type { Metadata } from "next";
import localFont from "next/font/local";
// import { Poppins } from "next/font/google";
import LenisGsap from "./dongsuh-2025/components/lenisGsap";
import "./dongsuh_globals.css";

const pretendard = localFont({
  src: "../../public/fonts/pretendard_gov_variable/PretendardGOVVariable.woff2",
  display:"swap",
  weight: "45 920",
  variable: "--font-pretendard"
});

// const poppins = Poppins({ 
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body 
        className={`${pretendard.variable} antialiased`} 
        style={{ borderTopStyle: 'solid' }} // gsap관련 hydration error 해결을 위해 추가
      >
        <LenisGsap>
        {children}  
        </LenisGsap>
        
    </body>
    </html>
  );
}
