import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const pretendard = localFont({
  src: "../../public/fonts/pretendard_gov_variable/PretendardGOVVariable.woff2",
  display:"swap",
  weight: "45 920",
  variable: "--font-pretendard"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body 
        className={`${pretendard.variable} antialiased`} 
        style={{ borderTopStyle: 'solid' }} // gsap관련 hydration error 해결을 위해 추가
      >
        <div className="page-wrap">
          {children}
        </div> 
    </body>
    </html>
  );
}
